// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omakqysytrojhojyblpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYWtxeXN5dHJvamhvanlibHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDU1MDMsImV4cCI6MjA3MDU4MTUwM30.gRdZue6Fs3Ie_weBBYBD6Nyy1Z972vxRAwGaAo7bUWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});